spring.application.name=event-management-system

server.port=9090

spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe?oracle.jdbc.mapDateToTimestamp=false
spring.datasource.username=EVENT_MGMT_ADMIN
spring.datasource.password=123456
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=none

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
# http://localhost:9090/swagger-ui/index.html

brevo.api.key=${BREVO_API_KEY}
brevo.sender.email=${BREVO_SENDER_EMAIL}
brevo.sender.name=${BREVO_SENDER_NAME}


# Booking expiry time in minutes
booking.expiration.minutes=15

# Scheduler operation (every minute)
booking.cancel.rate=60000

# Events update schedule (hourly)
event.update.cron=0 0 * * * *

management.endpoints.web.exposure.include=health,beans,info


spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

